name: example
description: A sample FFrame app. Use with caution.
version: 1.0.0+3

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.16.1 <4.0.0"

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
# TODO: to use this example, replace the fframe and froute dependency with
  # fframe:
  #     git:
  #       url: https://github.com/postmeridiem/fframe.git
  #       path: fframe/
  #       ref: main

  #Remove this fframe reference
  fframe:
    path: ../fframe

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  url_launcher: 
  intl: ^0.18.1
  flutterfire_ui: ^0.4.3+20
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 900
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-LightItalic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 900
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Italic.ttf
          style: italic
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 900

  assets:
    - assets/images/
    - assets/translations/
