linter:
  rules:
    avoid_print: false
    depend_on_referenced_packages: false
    library_private_types_in_public_api: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore