// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:fframe/fframe.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6aw2ddUvgh5zCc_iueyvi3mImvFPr0Ms',
    appId: '1:252859371693:web:5c67e3096937a7f1733624',
    messagingSenderId: '252859371693',
    projectId: 'fframe-dev',
    authDomain: 'fframe-dev.firebaseapp.com',
    databaseURL: 'https://fframe-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fframe-dev.appspot.com',
    measurementId: 'G-YM5SFM2J1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoLZ4FSdRWTs_YaSBRoBCooIc9F5YXqE4',
    appId: '1:252859371693:android:252c7330f8133e31733624',
    messagingSenderId: '252859371693',
    projectId: 'fframe-dev',
    databaseURL: 'https://fframe-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fframe-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADQDQu3GLCd9bzKBxc920b89LmveSNwu8',
    appId: '1:252859371693:ios:d7f6c916407edb6c733624',
    messagingSenderId: '252859371693',
    projectId: 'fframe-dev',
    databaseURL: 'https://fframe-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fframe-dev.appspot.com',
    iosClientId: '252859371693-uqler73an6ieehtai69cdbm44nd8t9ge.apps.googleusercontent.com',
    iosBundleId: 'fframe.app.fframeDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADQDQu3GLCd9bzKBxc920b89LmveSNwu8',
    appId: '1:252859371693:ios:cb0da463621a3c43733624',
    messagingSenderId: '252859371693',
    projectId: 'fframe-dev',
    databaseURL: 'https://fframe-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fframe-dev.appspot.com',
    iosClientId: '252859371693-oepn9hu631cd9pssqlhuau186jdqjs51.apps.googleusercontent.com',
    iosBundleId: 'fframe.app.example',
  );
}
