// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVHSodGvXZGkkBhqephehe7hlX-95oJq4',
    appId: '1:43505871602:web:397ec30942cac746f9fe6b',
    messagingSenderId: '43505871602',
    projectId: 'imagin-carfactory-dev',
    authDomain: 'imagin-carfactory-dev.firebaseapp.com',
    databaseURL: 'https://imagin-carfactory-dev.firebaseio.com',
    storageBucket: 'imagin-carfactory-dev.appspot.com',
    measurementId: 'G-28M08H9QG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSFZ0EwmmQpe-t-vPtfCAUflONkcuHqIk',
    appId: '1:43505871602:android:2bcfb71705496f6cf9fe6b',
    messagingSenderId: '43505871602',
    projectId: 'imagin-carfactory-dev',
    databaseURL: 'https://imagin-carfactory-dev.firebaseio.com',
    storageBucket: 'imagin-carfactory-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE85o305C7FVDGaZb8o2NCoO3e63b4qSo',
    appId: '1:43505871602:ios:985bdf9aba8a43edf9fe6b',
    messagingSenderId: '43505871602',
    projectId: 'imagin-carfactory-dev',
    databaseURL: 'https://imagin-carfactory-dev.firebaseio.com',
    storageBucket: 'imagin-carfactory-dev.appspot.com',
    androidClientId: '43505871602-51857r7ghemplpd1egrh7a8ovb3u4qch.apps.googleusercontent.com',
    iosClientId: '43505871602-cpfr7matft88dpki2qbve5tg8ud01b92.apps.googleusercontent.com',
    iosBundleId: 'studio.imagin.imgfactory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE85o305C7FVDGaZb8o2NCoO3e63b4qSo',
    appId: '1:43505871602:ios:985bdf9aba8a43edf9fe6b',
    messagingSenderId: '43505871602',
    projectId: 'imagin-carfactory-dev',
    databaseURL: 'https://imagin-carfactory-dev.firebaseio.com',
    storageBucket: 'imagin-carfactory-dev.appspot.com',
    androidClientId: '43505871602-51857r7ghemplpd1egrh7a8ovb3u4qch.apps.googleusercontent.com',
    iosClientId: '43505871602-cpfr7matft88dpki2qbve5tg8ud01b92.apps.googleusercontent.com',
    iosBundleId: 'studio.imagin.imgfactory',
  );
}
