name: fframe
description: The FlutFrame package.
version: 0.1.200+002
homepage: fframe.app

publish_to: none

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=3.19.2"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  firebase_core: 
  firebase_ui_oauth:
  firebase_ui_oauth_google:
  flutter_signin_button:
  google_sign_in:
  google_sign_in_web:
  firebase_auth:
  firebase_auth_web: 
  firebase_ui_auth:
  firebase_ui_firestore:
  firebase_ui_database:
  cloud_firestore: 
  firebase_storage:
  uuid: #to generate uids
  file_picker:
  firebase_analytics:
  clipboard:
  url_launcher: 
  cloud_functions:
  preload_page_view:
  shimmer:
  shared_preferences:
  horizontal_data_table: 
  dotted_border: 
  cached_network_image:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  # http:
  test:
  build_runner:
# The following section is specific to Flutter.
# === this is configured at the application level when using FlutFrame ===

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true