name: fframe
description: The FlutterFrame package .
version: 0.0.1
homepage: fframe.app

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  uuid:  #to generate uids
  flutter_signin_button: 
  google_sign_in:
  # googleapis:
  # googleapis_auth:
  flutterfire_ui: 
  file_picker: 
  go_router: 
  firebase_analytics: 
  flutter_riverpod:
  clipboard:
  cloud_functions:
  url_launcher:
  preload_page_view: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  http: 
  test: any
  build_runner:

# The following section is specific to Flutter.
# flutter:
#   uses-material-design: true
#   fonts:
#     - family: Raleway
#       fonts:
#         - asset: assets/fonts/Raleway-Regular.ttf
#         - asset: assets/fonts/Raleway-Italic.ttf
#           style: italic
#         - asset: assets/fonts/Raleway-Bold.ttf
#           weight: 900
#     - family: OpenSans
#       fonts:
#         - asset: assets/fonts/OpenSans-Light.ttf
#         - asset: assets/fonts/OpenSans-LightItalic.ttf
#           style: italic
#         - asset: assets/fonts/OpenSans-Regular.ttf
#           weight: 900
#     - family: Poppins
#       fonts:
#         - asset: assets/fonts/Poppins-Light.ttf
#         - asset: assets/fonts/Poppins-LightItalic.ttf
#           style: italic
#         - asset: assets/fonts/Poppins-Light.ttf
#           weight: 900
#     - family: RobotoMono
#       fonts:
#         - asset: assets/fonts/RobotoMono-Regular.ttf
#         - asset: assets/fonts/RobotoMono-Italic.ttf
#           style: italic
#         - asset: assets/fonts/RobotoMono-Bold.ttf
#           weight: 900

#   assets:
#     - assets/images/