name: fframe
description: The FlutFrame package.
version: 0.1.000+76
homepage: fframe.app

publish_to: none

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=3.19.2"

dependencies:
  flutter:
    sdk: flutter
  intl:
  cloud_firestore: 
  firebase_storage:
  uuid: #to generate uids
  flutter_signin_button:
  google_sign_in: 
  flutterfire_ui: 
  file_picker:
  firebase_analytics:
  flutter_riverpod: 
  clipboard:
  url_launcher: 
  cloud_functions:
  preload_page_view:
  shimmer:
  shared_preferences:
  horizontal_data_table: 
  dotted_border: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  # http:
  test:
  build_runner:
# The following section is specific to Flutter.
# === this is configured at the application level when using FlutFrame ===

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true