name: fframe
description: The FlutFrame package.
version: 0.1.0001
homepage: fframe.app

publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  # firebase_core:
  cloud_firestore:
  firebase_storage:
  uuid:  #to generate uids
  flutter_signin_button: 
  google_sign_in:
  # googleapis:
  # googleapis_auth:
  flutterfire_ui: 
  file_picker: 
  firebase_analytics: 
  flutter_riverpod:
  clipboard:
  url_launcher:
  cloud_functions:

  preload_page_view: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  http: 
  test: any
  build_runner:

# The following section is specific to Flutter.
# === this is configured at the application level when using FlutFrame ===